
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class connector extends javax.swing.JFrame {
     private static final String username="root";
     private static final String password="admin@123";
      private static final String dataConn="jdbc:mysql://localhost:3306/connector";
      Connection sqlConn=null;
      PreparedStatement pst=null;
      ResultSet rs=null;
      int q,i,id,deleteItem;

    /**
     * Creates new form connector
     */
    public connector() {
        initComponents();
    }
   
      
      
      public void upDateDB() 
      {
          try
          {
              Class.forName("com.mysql.jdbc.Driver");
              sqlConn=DriverManager.getConnection(dataConn,username,password);
              pst=sqlConn.prepareStatement("Select * from connector");
              rs=pst.executeQuery();
              ResultSetMetaData stData=rs.getMetaData();
              q=stData.getColumnCount();
              DefaultTableModel RecordTable=(DefaultTableModel)jTable2.getModel();
              RecordTable.setRowCount(0);
              while(rs.next())
              {
                  Vector columnData=new Vector();
                  for(i=1;i<=q;i++)
                  {
                      
                      columnData.add(rs.getString("id"));
                      columnData.add(rs.getString("studentid"));
                      columnData.add(rs.getString("firstname"));
                      columnData.add(rs.getString("surname"));
                      columnData.add(rs.getString("address"));
                      columnData.add(rs.getString("postcode"));
                      columnData.add(rs.getString("phone"));
                      
                  }
                  RecordTable.addRow(columnData);
              }
              
          }
          catch(Exception ex)
          {
              JOptionPane.showMessageDialog(null,ex);
          }
      }
      
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("phone");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("student id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("first name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("surname");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("post code");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 250, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 250, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 250, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 250, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 250, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 250, -1));

        jButton1.setText("add new");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jButton3.setText("print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        jButton4.setText("reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));

        jButton5.setText("delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        jButton6.setText("exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "student id", "firstname", "surname", "address", "postcode", "telephone"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 620, -1));

        setSize(new java.awt.Dimension(1514, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
          {
              Class.forName("com.mysql.jdbc.Driver");
              sqlConn=DriverManager.getConnection(dataConn,username,password);
              pst=sqlConn.prepareStatement("insert into connector(studentid,firstname,surname,address,"
                      +"postcode,phone)value"
                      +"(?,?,?,?,?,?)");
              pst.setString(1,jTextField1.getText());
              pst.setString(2,jTextField2.getText());
              pst.setString(3,jTextField3.getText());
              pst.setString(4,jTextField4.getText());
              pst.setString(5,jTextField5.getText());
              pst.setString(6,jTextField6.getText());
              pst.executeUpdate();
              JOptionPane.showMessageDialog(this,"Record Added");
              upDateDB();
          }
         catch(ClassNotFoundException | SQLException ex)
         {
             java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
          {
              Class.forName("com.mysql.jdbc.Driver");
              sqlConn=DriverManager.getConnection("jdbc:mysql://localhost:3306/connector","root","admin@123");
              pst=sqlConn.prepareStatement("update connector set studentid=?,firstname=?,surname=?,"
              +"address=?,postcode=?,telephone=? where id=?");
              pst.setString(1,jTextField1.getText());
              pst.setString(2,jTextField2.getText());
              pst.setString(3,jTextField3.getText());
              pst.setString(4,jTextField4.getText());
              pst.setString(5,jTextField5.getText());
              pst.setString(6,jTextField6.getText());
              pst.executeUpdate();
              JOptionPane.showMessageDialog(this,"Record Updated");
              upDateDB();
          }
         catch(ClassNotFoundException | SQLException ex)
         {
             java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable=(DefaultTableModel)jTable2.getModel();
            int SelectedRows=jTable2.getSelectedRow();
            jTextField1.setText(RecordTable.getValueAt(SelectedRows,1).toString()  );
            jTextField2.setText(RecordTable.getValueAt(SelectedRows,2).toString()  );
            jTextField3.setText(RecordTable.getValueAt(SelectedRows,3).toString()  );
            jTextField4.setText(RecordTable.getValueAt(SelectedRows,4).toString()  );
            jTextField5.setText(RecordTable.getValueAt(SelectedRows,5).toString()  );
            jTextField6.setText(RecordTable.getValueAt(SelectedRows,6).toString()  );
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Printing in progress");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try
        {
            jTable2.print(JTable.PrintMode.NORMAL,header,footer);
            
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("no printer found",e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable=(DefaultTableModel)jTable2.getModel();
            int SelectedRows=jTable2.getSelectedRow();
            try
            {
                id=Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString() );
                deleteItem=JOptionPane.showConfirmDialog(null,"confirm if you want to delete item",
                        "Warning",JOptionPane.YES_NO_OPTION);
                if(deleteItem==JOptionPane.YES_NO_OPTION)
                  {
                    Class.forName("com.mysql.jdbc.Driver");
              sqlConn=DriverManager.getConnection(dataConn,username,password);
              pst=sqlConn.prepareStatement("delete from connector where id=?");
              pst.setInt(1,id);
              
              pst.executeQuery();
              JOptionPane.showMessageDialog(this,"record updated");
              upDateDB();
              jTextField1.setText("");
              jTextField2.requestFocus();
              jTextField3.setText("");
              jTextField4.setText("");
              jTextField5.setText("");
              jTextField6.setText("");
                }
                
            }
            catch(ClassNotFoundException | SQLException ex)
         {
             java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
